server.port=8083
spring.application.name=vehicle-service
spring.config.import=optional:configserver:http://localhost:8888
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/greencarwash_vehicle_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Sathya@123}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
