package com.greencarwash.booking.entity;

public enum BookingStatus {
    CREATED,
    PAYMENT_PENDING,
    PAYMENT_SUCCESS,
    ASSIGNMENT_PENDING,
    WASHER_ASSIGNED,
    WASHER_ACCEPTED,
    WASHER_REJECTED,
    WASHER_REASSIGNMENT,
    WASHER_ON_THE_WAY,
    WASHER_ARRIVED,
    SERVICE_STARTED,
    SERVICE_IN_PROGRESS,
    VERIFICATION_PENDING,
    SERVICE_COMPLETED,
    CUSTOMER_SATISFIED,
    DISPUTED,
    CANCELLED,
    REFUNDED,
    CLOSED
}
